"""init

Revision ID: 28cb64f60f16
Revises: 
Create Date: 2026-04-27 10:20:52.819817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28cb64f60f16'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'TRANSCRIBING', 'SUMMARIZING', 'DONE', 'FAILED', name='meeting_status'), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('audio_path', sa.String(length=1000), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('speakers',
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('speaker_id', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meeting_id', 'speaker_id')
    )
    op.create_table('summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('exec_summary', sa.Text(), nullable=False),
    sa.Column('action_items_json', sa.JSON(), nullable=False),
    sa.Column('decisions_json', sa.JSON(), nullable=False),
    sa.Column('minutes_json', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_summaries_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('transcripts',
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.Column('plain_text', sa.Text(), nullable=False),
    sa.Column('words_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meeting_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcripts')
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_summaries_meeting_id'))

    op.drop_table('summaries')
    op.drop_table('speakers')
    op.drop_table('meetings')
    # ### end Alembic commands ###
