"""add series tags glossary speaker_names plus summary new fields

Revision ID: 98bfcb3b85de
Revises: d0a00e44b3bb
Create Date: 2026-04-27 19:40:48.294325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98bfcb3b85de'
down_revision: Union[str, Sequence[str], None] = 'd0a00e44b3bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email_tone', sa.Enum('FORMAL', 'CASUAL', name='email_tone'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_series_name')
    )
    op.create_table('tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_tag_name')
    )
    op.create_table('series_keyterms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('series_id', sa.String(length=36), nullable=False),
    sa.Column('term', sa.String(length=80), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'SUGGESTED', 'ACCEPTED', name='keyterm_source'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'term', name='uq_series_keyterm')
    )
    with op.batch_alter_table('series_keyterms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_keyterms_series_id'), ['series_id'], unique=False)

    op.create_table('series_speaker_names',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('series_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'display_name', name='uq_series_speaker_name')
    )
    with op.batch_alter_table('series_speaker_names', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_speaker_names_series_id'), ['series_id'], unique=False)

    op.create_table('meeting_tags',
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meeting_id', 'tag_id')
    )
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('series_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_meetings_series_id'), ['series_id'], unique=False)
        batch_op.create_foreign_key('fk_meetings_series_id', 'series', ['series_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qa_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('open_questions_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('email_draft', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('email_subject', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('email_tone', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.drop_column('email_tone')
        batch_op.drop_column('email_subject')
        batch_op.drop_column('email_draft')
        batch_op.drop_column('open_questions_json')
        batch_op.drop_column('qa_json')

    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_meetings_series_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_meetings_series_id'))
        batch_op.drop_column('series_id')

    op.drop_table('meeting_tags')
    with op.batch_alter_table('series_speaker_names', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_speaker_names_series_id'))

    op.drop_table('series_speaker_names')
    with op.batch_alter_table('series_keyterms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_keyterms_series_id'))

    op.drop_table('series_keyterms')
    op.drop_table('tags')
    op.drop_table('series')
    # ### end Alembic commands ###
