"""add num_speakers and meeting_brief

Revision ID: d0a00e44b3bb
Revises: 28cb64f60f16
Create Date: 2026-04-27 11:39:59.615449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0a00e44b3bb'
down_revision: Union[str, Sequence[str], None] = '28cb64f60f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_speakers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('meeting_brief', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_column('meeting_brief')
        batch_op.drop_column('num_speakers')

    # ### end Alembic commands ###
